ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "cpf" TEXT;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "rg" TEXT;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "endereco" TEXT;
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "cep" TEXT;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "cpf" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "rg" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "endereco" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "cep" TEXT;
