-- AlterTable
ALTER TABLE "tenants" ADD COLUMN "creci" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tenants" ADD COLUMN "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tenants" ADD COLUMN "telefone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tenants" ADD COLUMN "endereco" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tenants" ADD COLUMN "cidade" TEXT NOT NULL DEFAULT '';
