import { Prisma } from '@prisma/client';

/** Campos de lead retornados pela API, incluindo o corretor dono (id + nome). */
export const leadSelect = {
  id: true,
  tipo: true,
  nome: true,
  telefone: true,
  email: true,
  origem: true,
  interesse: true,
  cidade: true,
  bairro: true,
  stage: true,
  prioridade: true,
  renda: true,
  tipoRenda: true,
  estadoCivil: true,
  orcamentoMax: true,
  quartosMin: true,
  vagasMin: true,
  prospeccao: true,
  tags: true,
  corretorId: true,
  corretor: { select: { id: true, name: true } },
  equipeId: true,
  equipe: { select: { id: true, name: true } },
  construtoraId: true,
  construtora: { select: { id: true, nome: true, cor: true } },
  empreendimentoId: true,
  empreendimento: { select: { id: true, nome: true, cidade: true } },
  analise: {
    select: {
      id: true,
      status: true,
      parecer: true,
      analistaId: true,
      analista: { select: { id: true, name: true } },
    },
  },
  /** Parecer de crédito mais recente (Status 1 da documentação). */
  documentacoes: {
    orderBy: { updatedAt: 'desc' },
    take: 1,
    select: {
      id: true,
      status1: true,
      status2: true,
      updatedAt: true,
    },
  },
  perdidoAt: true,
  motivoPerda: true,
  perdidoPorId: true,
  perdidoPor: { select: { id: true, name: true } },
  stageEnteredAt: true,
  lastMovementAt: true,
  lastStageChangeAt: true,
  lastTriagemAt: true,
  lastTarefaAt: true,
  lastAtividadeAt: true,
  prazoDueAt: true,
  alertaProximoAt: true,
  prazoAdiado: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.LeadSelect;

export type LeadEntity = Prisma.LeadGetPayload<{ select: typeof leadSelect }>;
