-- AlterTable
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "banco" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "agencia" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "contaBancaria" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "pix" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "representanteLegal" TEXT NOT NULL DEFAULT '';
